"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

DB_SCHEMA = os.getenv("DB_SCHEMA", "public").strip()
if not DB_SCHEMA or not DB_SCHEMA.replace("_", "").isalnum():
    raise ValueError("DB_SCHEMA must contain only letters, numbers, and underscores.")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-only-change-me")

PASSWORD_PEPPER = os.getenv("PASSWORD_PEPPER", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "tender.mak.mn",
    "127.0.0.1",
    "localhost",
]

CSRF_TRUSTED_ORIGINS = [
    "http://tender.mak.mn",
    "https://tender.mak.mn",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "api",
    "django_extensions", 
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# THIS IS OLD DATABASE CONFIGURATION, COMMENTED OUT FOR REFERENCE
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "maktendertest",
#         "USER": "maktendertest",
#         "PASSWORD": "<redacted>",
#         "HOST": "172.16.0.5",
#         "PORT": "3306", 
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "maktender"),
        "USER": os.getenv("DB_USER", "tender_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "sslmode": os.getenv("DB_SSLMODE", "prefer"),
            "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "5")),
            "options": f"-c search_path={DB_SCHEMA},public",
        },
    }
}

ERP_URL = os.getenv("ERP_URL", "https://erp.mak.mn").rstrip("/")
ERP_DB = os.getenv("ERP_DB", "mak")
ERP_AUTH_TIMEOUT = int(os.getenv("ERP_AUTH_TIMEOUT", "15"))
ERP_VERIFY_SSL = os.getenv("ERP_VERIFY_SSL", "true").strip().lower() in {"1", "true", "yes", "on"}

ERP_LOGIN = {
    "USERNAME": "hr_attendance@mak.mn",
    "PASSWORD": "Attendance123@",
    "DATABASE": ERP_DB,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'procurement@mak.mn'
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
TENDER_PUBLIC_URL = os.getenv('TENDER_PUBLIC_URL', 'http://127.0.0.1:3000')

#  "EmailConfiguration": {
#     "From": "procurement@mak.mn",
#     "SmtpServer": "smtp.office365.com",
#     "Port": 587,
#     "SenderName": "MAK Tender",
#     "SenderEmail": "procurement@mak.mn",
#     "Username": "procurement@mak.mn",
#     "Password": "<redacted>"
#     //"Mak2024+"
#   }, 

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Tender user IDs (not employee IDs). Empty by default: no broad employee access.
AUDIT_LOG_VIEWER_USER_IDS = {
    int(value.strip())
    for value in os.getenv("AUDIT_LOG_VIEWER_USER_IDS", "").split(",")
    if value.strip()
}
