# Generated by Django 6.0.2 on 2026-09-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_postgresql_compatibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tblaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actioncode", models.CharField(blank=True, max_length=10, null=True)),
                ("actionname", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tblaction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbladmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tbladmin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codetypeid", models.IntegerField(blank=True, null=True)),
                ("codename", models.CharField(blank=True, max_length=100, null=True)),
                ("tendertypeid", models.IntegerField(blank=True, null=True)),
                ("newnumber", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblcode",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblcomment",
            fields=[
                ("commentid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "commenttitle",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("commentdate", models.DateTimeField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=2000, null=True)),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("seen", models.IntegerField(blank=True, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblcomment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblconsumeorderline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expenseid", models.IntegerField(blank=True, null=True)),
                ("consumeid", models.IntegerField(blank=True, null=True)),
                ("lineid", models.IntegerField(blank=True, null=True)),
                ("warehouseid", models.IntegerField(blank=True, null=True)),
                ("locationid", models.IntegerField(blank=True, null=True)),
                ("productid", models.IntegerField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "actualqty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "productbarcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "productname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("status", models.IntegerField(blank=True, null=True)),
                (
                    "issueqty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "consumename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "date_field",
                    models.DateTimeField(blank=True, db_column="date_", null=True),
                ),
            ],
            options={
                "db_table": "tblconsumeorderline",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblcriteria",
            fields=[
                ("criteriaid", models.AutoField(primary_key=True, serialize=False)),
                ("criteriatypeid", models.IntegerField(blank=True, null=True)),
                (
                    "criterianame",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("weight", models.CharField(blank=True, max_length=50, null=True)),
                ("visible", models.IntegerField(blank=True, null=True)),
                (
                    "invitationid",
                    models.IntegerField(
                        blank=True, db_column="invitationid", null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblcriteria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblcriteriatype",
            fields=[
                ("criteriatypeid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "criteriatypename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tblcriteriatype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbldepartment",
            fields=[
                ("departmentid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "departmentname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "depcode",
                    models.CharField(
                        blank=True, db_column="depcode", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tbldepartment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblemailcc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "positionname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tblemailcc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblemp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField(blank=True, null=True)),
                ("empname", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "positionname",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "tblemp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblevaluation",
            fields=[
                ("evaluationid", models.AutoField(primary_key=True, serialize=False)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("empid", models.IntegerField(blank=True, null=True)),
                ("empname", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "positionname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("roleid", models.IntegerField(blank=True, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "tblevaluation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblfiles",
            fields=[
                ("fileid", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(blank=True, max_length=200, null=True)),
                ("fileext", models.CharField(blank=True, max_length=100, null=True)),
                ("filedata", models.TextField(blank=True, null=True)),
                ("filepath", models.CharField(blank=True, max_length=1000, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("filetype", models.CharField(blank=True, max_length=20, null=True)),
                ("sourceid", models.IntegerField(blank=True, null=True)),
                ("sourcetype", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tblfiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblfoldercase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documentname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fileid", models.IntegerField(blank=True, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tblfoldercase",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblinvevaluate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("criteriaid", models.IntegerField(blank=True, null=True)),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblinvevaluate",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblinvitation",
            fields=[
                ("invitationid", models.AutoField(primary_key=True, serialize=False)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("acceptdate", models.DateTimeField(blank=True, null=True)),
                ("opendate", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="description", max_length=10000, null=True
                    ),
                ),
                (
                    "invitationcode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("openby", models.CharField(blank=True, max_length=200, null=True)),
                ("note", models.CharField(blank=True, max_length=2000, null=True)),
                ("delayedby", models.CharField(blank=True, max_length=200, null=True)),
                ("delaynote", models.CharField(blank=True, max_length=2000, null=True)),
                ("rejectby", models.CharField(blank=True, max_length=200, null=True)),
                ("rejectnote", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "tblinvitation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblinvitationofvendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenderid", models.IntegerField(blank=True, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("salespoint", models.IntegerField(blank=True, null=True)),
                ("assetpoint", models.IntegerField(blank=True, null=True)),
                ("resourcepoint", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "approvedamount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("updated", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tblinvitationofvendor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblinvitationstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tblinvitationstatus",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbljoinwork",
            fields=[
                ("joinworkid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "joinworkcode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "joinworkname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("departmentid", models.IntegerField(blank=True, null=True)),
                ("tendertypeid", models.IntegerField(blank=True, null=True)),
                ("startdate", models.DateTimeField(blank=True, null=True)),
                ("enddate", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=2000, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=30, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbljoinwork",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbljoinworkofvendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("joinworkid", models.IntegerField(blank=True, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tbljoinworkofvendor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblljoinworkdoc",
            fields=[
                ("joindocid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "documentname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fileid", models.IntegerField(blank=True, null=True)),
                ("joinworkid", models.IntegerField(blank=True, null=True)),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tblljoinworkdoc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblmembertype",
            fields=[
                ("membertypeid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "membertypename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tblmembertype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblnotes",
            fields=[
                ("noteid", models.AutoField(primary_key=True, serialize=False)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=30, null=True)),
                ("website", models.CharField(blank=True, max_length=20, null=True)),
                ("electron", models.IntegerField(blank=True, null=True)),
                ("post", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblnotes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblorderlineallocate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmpid", models.IntegerField(blank=True, null=True)),
                ("orderid", models.IntegerField(blank=True, null=True)),
                ("lineid", models.IntegerField(blank=True, null=True)),
                ("fromwarehouseid", models.IntegerField(blank=True, null=True)),
                ("towarehouseid", models.IntegerField(blank=True, null=True)),
                (
                    "towarehousename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("productid", models.IntegerField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblorderlineallocate",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblpurchaseorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.IntegerField(blank=True, null=True)),
                (
                    "ordernumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("warehouseid", models.IntegerField(blank=True, null=True)),
                (
                    "warehousename",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "totalquantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("sectorid", models.IntegerField(blank=True, null=True)),
                ("sectorname", models.CharField(blank=True, max_length=500, null=True)),
                ("buyerid", models.IntegerField(blank=True, null=True)),
                ("buyername", models.CharField(blank=True, max_length=200, null=True)),
                ("orderdate", models.DateTimeField(blank=True, null=True)),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("vendorname", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tblpurchaseorder",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblpurchaseorderline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lineid", models.IntegerField(blank=True, null=True)),
                ("orderid", models.IntegerField(blank=True, null=True)),
                ("ordername", models.CharField(blank=True, max_length=200, null=True)),
                ("productid", models.IntegerField(blank=True, null=True)),
                ("productuom", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "productquantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "productbarcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "productname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "priceunit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("status", models.IntegerField(blank=True, null=True)),
                (
                    "actualqty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("locationid", models.IntegerField(blank=True, null=True)),
                (
                    "locationname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "locationbarcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "receiptqty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("warehouseid", models.IntegerField(blank=True, null=True)),
                ("istemp", models.IntegerField(blank=True, null=True)),
                (
                    "ordernumber",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "date_field",
                    models.DateTimeField(blank=True, db_column="date_", null=True),
                ),
            ],
            options={
                "db_table": "tblpurchaseorderline",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblpurchasetype",
            fields=[
                ("purchasetypeid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "purchasetypename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tblpurchasetype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblqoute",
            fields=[
                ("qouteid", models.AutoField(primary_key=True, serialize=False)),
                ("qoutedate", models.DateTimeField(blank=True, null=True)),
                (
                    "qouteamount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("deliveryday", models.IntegerField(blank=True, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("tenderid", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("deliverydate", models.DateTimeField(blank=True, null=True)),
                ("batchid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblqoute",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblrequire",
            fields=[
                ("requireid", models.AutoField(primary_key=True, serialize=False)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                (
                    "requirename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("visible", models.IntegerField(blank=True, null=True)),
                ("requiretypeid", models.IntegerField(blank=True, null=True)),
                ("criteriaid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblrequire",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblrequiretype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirevalue",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
            ],
            options={
                "db_table": "tblrequiretype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblrole",
            fields=[
                ("roleid", models.AutoField(primary_key=True, serialize=False)),
                ("rolename", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tblrole",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblsettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actionid", models.IntegerField(blank=True, null=True)),
                ("membertypeid", models.IntegerField(blank=True, null=True)),
                ("empid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblsettings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltender",
            fields=[
                ("tenderid", models.AutoField(primary_key=True, serialize=False)),
                ("tendercode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tendername",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("purchasetypeid", models.IntegerField(blank=True, null=True)),
                ("departmentid", models.IntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("evaluationdate", models.DateTimeField(blank=True, null=True)),
                ("publishdate", models.DateTimeField(blank=True, null=True)),
                ("startdate", models.DateTimeField(blank=True, null=True)),
                ("enddate", models.DateTimeField(blank=True, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("plandate", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbltender",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderbatch",
            fields=[
                ("batchid", models.AutoField(primary_key=True, serialize=False)),
                ("tenderid", models.IntegerField()),
                ("batchcode", models.CharField(blank=True, max_length=100, null=True)),
                ("batchname", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tbltenderbatch",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderdelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delayedby", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "delayednote",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("acceptdate", models.DateTimeField(blank=True, null=True)),
                ("opendate", models.DateTimeField(blank=True, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbltenderdelay",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderdoc",
            fields=[
                ("docid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "documentcode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "documentname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("doctypeid", models.IntegerField(blank=True, null=True)),
                ("fileid", models.IntegerField(blank=True, null=True)),
                ("batchid", models.IntegerField(blank=True, null=True)),
                ("tenderid", models.IntegerField(blank=True, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "tbltenderdoc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderdoctype",
            fields=[
                ("doctypeid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "doctypename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tbltenderdoctype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderjoindoc",
            fields=[
                ("joindocid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "documentname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fileid", models.IntegerField(blank=True, null=True)),
                ("tenderid", models.IntegerField(blank=True, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("createdby", models.CharField(blank=True, max_length=100, null=True)),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                ("requiretypeid", models.IntegerField(blank=True, null=True)),
                ("batchid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbltenderjoindoc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("invitationid", models.IntegerField(blank=True, null=True)),
                ("membertypeid", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbltenderopen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltendertype",
            fields=[
                ("tendertypeid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tendertypename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tbltendertype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltenderuser",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("empid", models.IntegerField(blank=True, null=True)),
                ("empname", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "positionname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vendorid", models.IntegerField(blank=True, null=True)),
                (
                    "passwordsalt",
                    models.CharField(
                        blank=True, db_column="passwordsalt", max_length=50, null=True
                    ),
                ),
                (
                    "passwordhash",
                    models.CharField(
                        blank=True, db_column="passwordhash", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tbltenderuser",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltransitorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transitid", models.IntegerField(blank=True, null=True)),
                ("transferdate", models.DateTimeField(blank=True, null=True)),
                ("fromwarehouseid", models.IntegerField(blank=True, null=True)),
                (
                    "fromwarehousename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("towarehouseid", models.IntegerField(blank=True, null=True)),
                (
                    "towarehousename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("status", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbltransitorder",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltransitorderline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lineid", models.IntegerField(blank=True, null=True)),
                ("transitid", models.IntegerField(blank=True, null=True)),
                ("purchaseorderid", models.IntegerField(blank=True, null=True)),
                ("productid", models.IntegerField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "productbarcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "productname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("status", models.IntegerField(blank=True, null=True)),
                (
                    "actualqty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "transqty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "transitname",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "date_field",
                    models.DateTimeField(blank=True, db_column="date_", null=True),
                ),
            ],
            options={
                "db_table": "tbltransitorderline",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblvendor",
            fields=[
                ("vendorid", models.AutoField(primary_key=True, serialize=False)),
                ("vendorname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "registernumber",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("isvatpayer", models.IntegerField(blank=True, null=True)),
                ("vendortypeid", models.IntegerField(blank=True, null=True)),
                (
                    "countryname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("establisheddate", models.DateTimeField(blank=True, null=True)),
                ("activity", models.CharField(blank=True, max_length=500, null=True)),
                ("vendorstatusid", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "vendorphone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vendoremail",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bankname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bankaccountname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "bankaccountnumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created", models.CharField(blank=True, max_length=100, null=True)),
                ("empname", models.CharField(blank=True, max_length=200, null=True)),
                ("empphone", models.CharField(blank=True, max_length=200, null=True)),
                ("empemail", models.CharField(blank=True, max_length=200, null=True)),
                ("updated", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "headcompany",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("website", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "shareholder",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "verification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tblvendor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblvendoractivity",
            fields=[
                ("activityid", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tblvendoractivity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblvendorcategoryrel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erpcategoryid", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tblvendorcategoryrel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TenderEvaluationStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tender_evaluation_status",
            },
        ),
        migrations.CreateModel(
            name="TenderVendorEvaluation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tenderid", models.IntegerField()),
                ("vendorid", models.IntegerField()),
                ("invitationid", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        db_column="statusid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="api.tenderevaluationstatus",
                    ),
                ),
            ],
            options={
                "db_table": "tender_vendor_evaluation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenderid", "vendorid"),
                        name="unique_tender_vendor_evaluation",
                    )
                ],
            },
        ),
    ]
